import Footer from "@/app/(commonLayout)/components/shared/Footer";
import NavBar from "@/app/(commonLayout)/components/shared/Navbar";
import type { Metadata } from "next";
import AdminSidebar from "./components/Sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default async function userDashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <NavBar />
      <AdminSidebar></AdminSidebar>
      <main className="min-h-screen max-w-screen-xl	mx-auto">{children}</main>
      <Footer />
    </div>
  );
}
