import type { Metadata } from "next";
import NavBar from "./components/shared/Navbar";
import Footer from "./components/shared/Footer";
import { userInfo } from "./action/userInfo";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function CommonLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user= await userInfo()

  return (
    <div>
      {/* <p>Navbar</p> */}
      <NavBar user={user}></NavBar>
      <div className="mx-auto container ">{children}</div>
      {/* <p>footer</p> */}
      <Footer></Footer>
    </div>
  );
}
